# Generated by Django 3.2.5 on 2021-07-19 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_analysis', models.TextField(max_length=2000, verbose_name='Phân tích tổng thể')),
                ('upcoming_event', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lịch Kinh tế')),
                ('trade_note', models.TextField(verbose_name='Đánh giá điểm trade')),
                ('htf_image', models.ImageField(blank=True, null=True, upload_to='upload/images/')),
                ('ttf_image', models.ImageField(blank=True, null=True, upload_to='upload/images/')),
                ('ltf_image', models.ImageField(blank=True, null=True, upload_to='upload/images/')),
                ('entry_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10, verbose_name='Loại')),
                ('entry_time', models.DateTimeField(blank=True, null=True, verbose_name='Giờ mở lệnh')),
                ('entry_price', models.DecimalField(decimal_places=5, default=0, max_digits=5, verbose_name='Giá mở lệnh')),
                ('entry_sl', models.DecimalField(decimal_places=5, default=0, max_digits=5, verbose_name='Giá SL')),
                ('entry_tp', models.DecimalField(decimal_places=5, default=0, max_digits=5, verbose_name='giá TP')),
                ('during_trade_analysis', models.TextField(max_length=2000, verbose_name='Phân tích trong khi trade')),
                ('closing_price', models.DecimalField(decimal_places=5, default=0, max_digits=5, verbose_name='Giá đóng lệnh')),
                ('closing_time', models.DateTimeField(blank=True, null=True, verbose_name='Giờ đóng lệnh')),
                ('trade_image', models.ImageField(upload_to='upload/images/')),
                ('post_analysis', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Phân tích sau trade')),
                ('symbol_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='journal', to='trade.symbol', verbose_name='Cặp tiền')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trader', to=settings.AUTH_USER_MODEL, verbose_name='Trader')),
            ],
            options={
                'verbose_name_plural': 'Journal',
            },
        ),
    ]
